version: '3.3'

services:
  db:
    image: postgres:12.0-alpine
    #env_file:
    #  - database.env
    
    environment:
       - POSTGRES_DB=ez_delivery
       - POSTGRES_USER=ez_user
       - POSTGRES_PASSWORD=somepwd123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      - "PGADMIN_DEFAULT_EMAIL=tech@arabeasy.com"
      - "PGADMIN_DEFAULT_PASSWORD=1234"
      - "PGADMIN_LISTEN_PORT=80"
    ports:
      - "8080:80"
    volumes:
      - "pgadmin-data:/var/lib/pgadmin-data"


networks:
  app-network:
    driver: bridge


volumes:
 postgres_data:
 pgadmin-data:
